### ISSUE TITLE
Part 15. Sign-in      "Request Failed with status code 401"

### ISSUE THREAD

**Issue by Dallas-Alfonso** [basir/node-react-ecommerce#127]
Hello Basir, the tutorial is amazing, thank you!  I dont think this question is covered yet but, every-time I Sign-In, the web browser returns "Request Failed with status code 401".  

When I inspect the issue, it says that email and password are not correct even though they are.  On your video, you had the same issue, but you didnt get to go over that.(3:45:25)  At first, I thought that it was because I dont have mongodb downloaded properly, but it seems I do.  Would you know how I can fix this issue? 

Additional Info: The terminals (front end & backend) is working properly with no errors.

**Comment by sofie-morling** [comment]
I have the same issue when I am trying to sign in my user. Have watched the video three times now and can't seem to find the problem  😥

**Comment by sharmi16** [comment]
i also have the same..is anyone fixed it

**Comment by Dallas-Alfonso** [comment]
My advice would be, to leave this tutorial and move on to the updated version on youtube!
