### ISSUE TITLE
Where/How to Delete MongoDB?

### ISSUE THREAD

**Issue by windowshopr** [basir/node-react-ecommerce#150]
This is probably a stupid question and isn't really an "issue", but long story short, I downloaded this repo and ran it/created an admin account already. Then I haven't used the app for a while, and re-downloaded another copy of it to a different folder location. When I try to create a new admin account (email/pass) I get the same error as in #49 , so I want to follow the advice there and start fresh, but where is the mongodb stored for me to do that?

Thanks!

**Comment by textbook-haroon** [comment]
Hey, @windowshopr, have you solved that issue? I was also stuck there. Thanks.

**Comment by windowshopr** [comment]
Unfortunately no, we ended up going a different way and didn’t have a need for this project. I’m a newb when it comes to that database so I don’t have an answer for ya. Sorry!

**Comment by basir** [comment]
hello there,
in newer version of this app I fixed this issue:
check it out:
https://github.com/basir/mern-amazona
