### ISSUE TITLE
in Add to Cart button

### ISSUE THREAD

**Issue by navreet1999** [basir/node-react-ecommerce#25]
qty is not working properly,qty not showing the dropdown list to select the quantity.
and the condition written for Add to Cart working not properly that's why this button is not shoeing on the screen

**Comment by basir** [comment]
hello there, are you sure? the demo website works perfectly. can you mention the file and the line number to take a look

**Comment by navreet1999** [comment]
> hello there, are you sure? the demo website works perfectly. can you mention the file and the line number to take a look

now it running fine

**Comment by basir** [comment]
nice
