### ISSUE TITLE
Hii I am not able to configure node server in express

### ISSUE THREAD

**Issue by Ratna0310** [basir/node-react-ecommerce#42]
![Screenshot (1)](https://user-images.githubusercontent.com/53630434/84375433-2e4b8c00-abfd-11ea-8e6c-a733569e163d.png)

**Comment by basir** [comment]
hello there
Share your code on GitHub to take a look.

**Comment by Ratna0310** [comment]
https://github.com/Horizon03/Ecommerece-app.git
please have a look on it.

**Comment by basir** [comment]
Send me a message over Skype to set a short call to fix your issue . My
Skype is basir.jafarzadeh

**Comment by Ratna0310** [comment]
thanks.
