### ISSUE TITLE
problem with mongodb cannot get connected 

### ISSUE THREAD

**Issue by Yassineaeh** [basir/node-react-ecommerce#46]
ive changed it to mongoAtlas the mongo to connect it via the cloud but it gives me this issue 
ps : it didnt work with mongodb because i have it already installed but i dont know how to create another database

**Comment by basir** [comment]
First don’t share your database password
Second you wrapped your db name, password between <> . Get rid of them

**Comment by Yassineaeh** [comment]
ive got rid of them but it still gaves me the same error !

**Comment by basir** [comment]
Try to connect to your database with this sample code:

const mongoose = require('mongoose'); mongoose.connect('your-connection',
{useNewUrlParser: true, useUnifiedTopology: true}); const Cat =
mongoose.model('Cat', { name: String }); const kitty = new Cat({ name:
'Zildjian' }); kitty.save().then(() => console.log('meow'));

If it doesn't work, you need to fix your connection.

**Comment by basir** [comment]
did it fix?

**Comment by Yassineaeh** [comment]
i dont know where to put this code in order to see if it does work ! 
i want to know if the data you're getting after you install mongo in the tutorial is fetched from the database or the server ?
if its the case should i import data.js manually to mongodb in order to fix it ?

**Comment by Yassineaeh** [comment]
to be precise when i downloaded the version : Video-16-Manage-Products-Screen (#14)
i couldnt fetch the data from the database !

**Comment by Yassineaeh** [comment]
it's been solved thanks !

**Comment by basir** [comment]
glad to hear that.

**Comment by basir** [comment]
> i dont know where to put this code in order to see if it does work !
> i want to know if the data you're getting after you install mongo in the tutorial is fetched from the database or the server ?
> if its the case should i import data.js manually to mongodb in order to fix it ?

you need to put that code in an empty test.js file and run it like `node test.js` to make sure you get no error in console.
