### ISSUE TITLE
{"msg":"E11000 duplicate key error collection: amazona.users index: email_1 dup key: { email: \"basir.jafarzadeh@gmail.com\" }"}

### ISSUE THREAD

**Issue by brijesh1488** [basir/node-react-ecommerce#49]
Please resolve problem {"msg":"E11000 duplicate key error collection: amazona.users index: email_1 dup key: { email: \"basir.jafarzadeh@gmail.com\" }"}
![image](https://user-images.githubusercontent.com/33192142/84775147-72bf9900-affc-11ea-80f2-0711854da807.png)
![image](https://user-images.githubusercontent.com/33192142/84775553-fe392a00-affc-11ea-9035-c0e9d90d65ea.png)
![image](https://user-images.githubusercontent.com/33192142/84842827-cb764c80-b063-11ea-82e2-c43be2793960.png)

**Comment by brijesh1488** [comment]
plz help in this

**Comment by basir** [comment]
Delete your mongodb database and check again. Or you can change email to
prevent duplicate error.

**Comment by brijesh1488** [comment]
this error is also come... it is not login plz help
POST http://localhost:3000/api/users/signin 401 (Unauthorized)

![image](https://user-images.githubusercontent.com/33192142/84898906-98fd3b80-b0c5-11ea-801d-255964a762eb.png)

**Comment by basir** [comment]
This error means your user and pass do not match on the database. first create an account then try again.

**Comment by brijesh1488** [comment]
plz check the database detail.. we make user and password

![image](https://user-images.githubusercontent.com/33192142/85193454-45b60380-b2e6-11ea-87ef-a32b775c8b00.png)

**Comment by brijesh1488** [comment]
after click on submit button loading is showing
plz help i am fresher in this field

![image](https://user-images.githubusercontent.com/33192142/85196678-83705780-b2f9-11ea-869d-a8726cf38b31.png)

**Comment by basir** [comment]
Please show me the result of this API and teminal output

**Comment by brijesh1488** [comment]
![image](https://user-images.githubusercontent.com/33192142/85200699-4e72fd80-b317-11ea-98eb-d0db6002bd3c.png)

**Comment by brijesh1488** [comment]
download code here  https://drive.google.com/file/d/1dwVsl39EVqsw1cbmOaRk0OOmGBwLgUZX/view?usp=sharing

**Comment by basir** [comment]
lets have skype call with screen sharing to fix your issue. my skype name is basir.jafarzadeh

**Comment by brijesh1488** [comment]
thank you for solving my problem....
