### ISSUE TITLE
POST http://localhost:3000/api/users/signin 401 (Unauthorized)

### ISSUE THREAD

**Issue by brijesh1488** [basir/node-react-ecommerce#52]
Sign problem is come... plz resolve 
![image](https://user-images.githubusercontent.com/33192142/84968683-bae1d700-b134-11ea-8ff7-aa22a64d5d32.png)
![image](https://user-images.githubusercontent.com/33192142/84968790-f11f5680-b134-11ea-98a2-523847c97072.png)

**Comment by brijesh1488** [comment]
plz reply on it....

**Comment by basir** [comment]
did it fix?

**Comment by brijesh1488** [comment]
no

**Comment by basir** [comment]
did you follow this https://gist.github.com/basir/d121df24c47861e13a1cdcbed1cca902?

**Comment by brijesh1488** [comment]
thank you for helping me....

**Comment by UzalKhadka** [comment]
im having same error too.. being a beginner, im not able to solve the problem. help me. @brijesh1488  @basir

**Comment by Volpone24** [comment]
Was the error solved? Can you tell me how
