### ISSUE TITLE
Not getting info from console 

### ISSUE THREAD

**Issue by RuiLopes98** [basir/node-react-ecommerce#54]
Hello!

This is my first time working with React and Node.

I'm following this tutorial for my first profissional website. 
https://youtu.be/Fy9SdZLBTOo?t=4568 (1:16:07)

And I'm not getting the value 1 as a return in the Chorme console in the developer tools.

![error_console](https://user-images.githubusercontent.com/67196990/85204657-da802780-b30d-11ea-9eb7-565141d318f8.png)

I would be super thankfull if you could help me! :D 

Thanks for the attention.

**Comment by basir** [comment]
hello there
share you code on github to take a look.

**Comment by RuiLopes98** [comment]
> hello there
> share you code on github to take a look.

https://github.com/RuiLopes98/ecommercetry

Here's the code, I still have the node_modules folder, but it's to heavy to upload in here (more than 25MB)

**Comment by basir** [comment]
change 
<Route path="/products/:id" component={ProductScreen} />
to
<Route path="/product/:id" component={ProductScreen} />

**Comment by RuiLopes98** [comment]
> change
> 
> to

Sorry, but I can't see what you wrote :( 
![ffe81b175987ed298fdbaca0238d2b12](https://user-images.githubusercontent.com/67196990/85209750-52f8df80-b332-11ea-8ac3-a5ef4393f8a1.png)

**Comment by lipsray** [comment]
i had the exactly same problem =( waiting for the clue

**Comment by basir** [comment]
change
    <Route path="/products/:id" component={ProductScreen} />
      
to     <Route path="/product/:id" component={ProductScreen} />

**Comment by basir** [comment]
```
change
<Route path="/products/:id" component={ProductScreen} />
to
<Route path="/product/:id" component={ProductScreen} />
      
```

**Comment by basir** [comment]
change
path="/products/:id" component={ProductScreen} 
ro
path="/product/:id" component={ProductScreen}

**Comment by lipsray** [comment]
worked. thank you <3

**Comment by RuiLopes98** [comment]
> change
> path="/products/:id" component={ProductScreen}
> ro
> path="/product/:id" component={ProductScreen}



It worked for me! 

Thanks for the help! Going to follow do tutorial
