### ISSUE TITLE
Error with the prop

### ISSUE THREAD

**Issue by OswalDev** [basir/node-react-ecommerce#55]
![2020-06-20 17_01_51-React App](https://user-images.githubusercontent.com/26017333/85213947-02ce4d00-b333-11ea-86c2-d03fd45539e3.png)

Hi, i need some help. i'm getting this error while watching the react router part since yesterday and i don't know how to fix it.

Thank you for your videos :3.

**Comment by OswalDev** [comment]
nevermind, i already fixed it.

**Comment by basir** [comment]
sounds good.
