### ISSUE TITLE
Node backend start error 

### ISSUE THREAD

**Issue by RuiLopes98** [basir/node-react-ecommerce#61]
Hey there again!

I'm getting this error: 
![error_cmd](https://user-images.githubusercontent.com/67196990/85428774-9e4f0000-b575-11ea-915e-cc362d6b0c6b.png)~

When trying to execute: node backend/server.js.

This is my server.js code: 
```
import express from 'express';
import data from './data';

const app = express();


app.get("/api/products", (req, res) => {
    res.send(data.products);
});

app.listen(5000, () => {
    console.log("server started at at http://localhost:5000");
});
```

If someone can help and need extra code or information, please tell me and i'll provide it as fast as possible!

Thanks for the attention!!

**Comment by basir** [comment]
You did not set babel correctly to transpile ES6 code to ES5. Follow this:
https://gist.github.com/basir/d121df24c47861e13a1cdcbed1cca902#cannot-use-import-statement-outside-of-a-module
