### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by OswalDev** [basir/node-react-ecommerce#64]
I don't know what's causing this error, i've cheked all of the hooks used
![2020-06-23 22_33_34-Settings](https://user-images.githubusercontent.com/26017333/85492893-eb49cb00-b5a3-11ea-9e68-075feb4a8d8d.png)
![2020-06-23 22_32_33-Settings](https://user-images.githubusercontent.com/26017333/85492901-edac2500-b5a3-11ea-856d-f44260a36721.png)

**Comment by basir** [comment]
share your code on github as new repo to take a look.

**Comment by OswalDev** [comment]
https://github.com/OswalDev/Proyect_Shopliest

I was in the part 11 of the video, maybe i'm missing something, but i couldn't find where

**Comment by OswalDev** [comment]
I already fixed it, sorry. I was calling no funtion in the ProductScreen dispatch and made a small typo declaring one variable at ProductReducers.
