### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by RuiLopes98** [basir/node-react-ecommerce#67]
Hello there, I'm having this error 

![error_property](https://user-images.githubusercontent.com/67196990/85744881-24498300-b6fd-11ea-8407-08466c2a78fb.png)

following the tutorial at this time:
https://youtu.be/Fy9SdZLBTOo?t=6043 

Trying to run the frontend app again.

Thankful if someone could help, thanks for the attention!

**Comment by basir** [comment]
share your server.js please
