### ISSUE TITLE
subtotal not adding up

### ISSUE THREAD

**Issue by oyeyipo45** [basir/node-react-ecommerce#68]
The subtotal does not add up when the value of qty is changed in the cart screen instead it concatenates.
This error can be noticed at 3:07:13 of the project. thank you.

![Screenshot (50)](https://user-images.githubusercontent.com/51447719/85886967-de64eb80-b7de-11ea-9a9f-18fe150e18ef.png)

**Comment by basir** [comment]
hello there, you are right. you need to cast the selected qty to number like this:
const num = Number(qty)

**Comment by oyeyipo45** [comment]
solved, thank you
