### ISSUE TITLE
OnChange is not working in cartScreen.js

### ISSUE THREAD

**Issue by ashiqchinju** [basir/node-react-ecommerce#71]
While changing the quantity in cart it is not changing. Previous value is being previewed everytime i change the value. 
My code:
<select value={item.qty} onChange={(e) => dispatch(addToCart(item.product, e.target.value))}>
                      {[...Array(item.countInStock).keys()].map(x =>
                        <option key={x + 1} value={x + 1}>{x + 1}</option>
                      )}
                    </select>

**Comment by mHamza301** [comment]
What name you have used to declare countInStock in cartaction.js? 

I got the same issue, and it was i was not using the correct name for countInStock  for item.CountInStock

**Comment by basir** [comment]
> What name you have used to declare countInStock in cartaction.js?
> 
> I got the same issue, and it was i was not using the correct name for countInStock for item.CountInStock

did it fix?
