### ISSUE TITLE
Error: ENOENT: no such file or directory, stat

### ISSUE THREAD

**Issue by bohdan-vyshynskyi** [basir/node-react-ecommerce#93]
Hello! Trying to deal with such error while deplying on Heroku. Application runs correctly on localhost, cloud MongoDB connected. Followed all instructions for deploying on Heroku, but the problem has been not fixed.
Also I tried solution from **Amazona FAQ** with using _**npm run build**_, but the error didn't disappear.
Project folders:
- backend
-- server.js
-- ...
- frontend
-- public
--- index.js
--- ...
-- ...
- ...
Complete last log:

_2020-07-23T15:17:25.059574+00:00 app[web.1]: Error: ENOENT: no such file or directory, stat '/app/frontend/build/index.html'
2020-07-23T15:17:25.059800+00:00 heroku[router]: at=info method=GET path="/" host=benerous-cook-book-app.herokuapp.com request_id=07be5da5-adeb-4342-a960-86a6adbfc113 fwd="93.75.244.38" dyno=web.1 connect=1ms service=6ms status=404 bytes=380 protocol=https
PS C:\Users\bogda\OneDrive\Рабочий стол\Work\Projects\react_projects\react-cook-book>_ 

I would be glad to get a solution from you or other people who faced with similar error while deploying on Heroku.
Thank you!

**Comment by bohdan-vyshynskyi** [comment]
Problem was caused by git repository in frontend. While pushing to heroku/github frontend folder was shown as git submodule of main folder. So path to _index.html_ was not found, as such repository while deploying/pushing was not created.
Solution: in main repository **should not be any git submodules.**

**Comment by prabakardaniel** [comment]
Hi Benerous,

I don't understand here as what is submodules?

**Comment by prabakardaniel** [comment]
I don't understand here as what is git submodules?

**Comment by bohdan-vyshynskyi** [comment]
It means if you have **main** folder with git repository there shouldn't be any other folders inside **main** folder with another git repository.
So there should be only one git repository in project.
I had issue that **main** folder had it's git repo and frontend part had inside another one too.

**Comment by prabakardaniel** [comment]
Thanks Benerous.
