### ISSUE TITLE
Proxy error: Could not proxy request /api/products from localhost:3000 to http://127.0.0.1:5000.

### ISSUE THREAD

**Issue by ghost** [basir/node-react-ecommerce#98]
Hi Basir,

First of all, very good course.

Second, I have a problem :(.

I get this message in the terminal and Products page doesn't render any products, nor I can sign in or register user.
![Capture](https://user-images.githubusercontent.com/69052615/89063885-a1f25580-d371-11ea-8e29-a1c51826caf4.JPG)

Proxy error: Could not proxy request /api/users/register from localhost:3000 to http://127.0.0.1:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Can you please indicate what to look for?

**Comment by basir** [comment]
hello there
thanks
check this to fix it
https://gist.github.com/basir/d121df24c47861e13a1cdcbed1cca902#proxy-error-could-not-proxy-request-apiproducts
